### ISSUE TITLE
Shared token with limited bucket permissions spits out an error on page load

### ISSUE THREAD

**Issue by pivnicek** [keboola/storage-api-console#43] opened 2018-01-05 15:14 UTC
If I create a token for somebody and limit their permissions and share it with them.  When they visit the storage console they get an error.

![image](https://user-images.githubusercontent.com/569139/34614985-8412bb4e-f233-11e7-8b8e-6612ef897bdb.png)

**Comment by Halama** [comment] 2018-02-02 18:34
Duplicate of #31

**Closed by Halama** 2018-02-02 18:34 UTC
Labels: bug
